### ISSUE TITLE
float division by zero

### ISSUE THREAD

**Issue by YuhengRR** [praveena2j/RCMA#4]
/data/lyh/Affwild2/cropped_aligned/1-30-1280x720
Traceback (most recent call last):
  File "/home/sherry/lyh/RJCMA/abaw6_preprocessing/project/abaw5/main.py", line 18, in <module>
    pre.generate_per_trial_info_dict()
  File "/home/sherry/lyh/RJCMA/abaw6_preprocessing/project/abaw5/preprocessing.py", line 111, in generate_per_trial_info_dict
    this_trial['video_annotated_index'] = self.get_annotated_index(annotated_index, **get_annotated_index_kwargs)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherry/lyh/RJCMA/abaw6_preprocessing/project/abaw5/preprocessing.py", line 225, in get_annotated_index
    sampled_index = np.asarray(np.round(target_frequency / source_frequency * annotated_index), dtype=np.int64)
                                        ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero
Hello, I can not solve this problem, I do not know what is the reason? Can you help me to solve it?

**Comment by praveena2j** [comment]
I guess you need to debug the code, check the data in the variables before this line

**Comment by YuhengRR** [comment]
Ok, thanks for your answer, I'll take a closer look at the code, and by the way, when doing the preprocessing, is it the source dataset or the official cropped dataset that is used.

**Comment by praveena2j** [comment]
I have used the official cropped and aligned images provided by the organizers

**Comment by YuhengRR** [comment]
Okay, thanks again.

**Comment by muginekoo** [comment]
Maybe you should check the folder name of raw radios.
